# Generated by Django 5.2.8 on 2025-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_product_price_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
