# Generated by Django 5.2.8 on 2025-11-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_review_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='quantity',
        ),
    ]
